# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8feccc0ab9a0b4a3f25ab8806123cbb627d08669b60a7998d3b4bb66951751888c3b80e36d4699ac687ef7e5338a9be144135eaec81e89f3a19f4db070620cce

test:
  secret_key_base: 3ec9db4dd1d0fe98693edce13215ca5bb96d5ada7211b393a3f1a4d25c646bb3c67a4fd6e1acf157b6b9e946e5302c8f96cf304808a1f428a70e9d70272eb431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
